# Generated by Django 5.0.3 on 2024-03-10 21:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dbapp", "0002_productmodel_productmodeldocumenttypedocs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productmodel",
            name="link",
        ),
    ]
