# Generated by Django 5.0.3 on 2024-03-10 22:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dbapp", "0004_producttype_alter_productmodel_brand"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productmodel",
            old_name="brand",
            new_name="product",
        ),
    ]
