# Generated by Django 5.0.3 on 2024-03-11 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dbapp", "0005_rename_brand_productmodel_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category",
                to="dbapp.brand",
            ),
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_content", models.TextField()),
                ("title", models.CharField(blank=True, max_length=5000, null=True)),
                ("text", models.TextField()),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="pdfs/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "doc",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doc_article",
                        to="dbapp.productmodeldocumenttypedocs",
                    ),
                ),
            ],
        ),
    ]
