# Generated by Django 5.0.3 on 2024-03-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dbapp", "0006_alter_category_brand_article"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
