# Generated by Django 5.0.3 on 2024-03-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manua", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="link",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="link",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
